--CREATE DATABASE projeto_COVID19;
--USE projeto_COVID19;

CREATE TABLE PAIS

(
	ID_Código_ISO2	VARCHAR(2)	NOT NULL,
	NOME			VARCHAR(50)	NOT NULL,
	CONSTRAINT	PK_PAIS	PRIMARY KEY (ID_Código_ISO2)
);

CREATE TABLE CASOS_CONFIRMADOS

(
	ID						INT 		NOT NULL IDENTITY(1,1),
	ID_PAIS					VARCHAR(2)	NOT NULL,
	N_CASOS_CONFIRMADOS		INT			NOT NULL,
	DATA					DATETIME	NOT NULL,
	CONSTRAINT PK_CASOS_CONFIRMADOS PRIMARY KEY (ID),
	CONSTRAINT FK_CASOS_CONFIRMADOS_PAIS FOREIGN KEY (ID_PAIS)
	REFERENCES PAIS(ID_Código_ISO2)
);

CREATE TABLE MORTES

(
	ID			INT			NOT NULL IDENTITY(1,1),
	ID_PAIS		VARCHAR(2)	NOT NULL,
	N_MORTES	INT			NOT NULL,
	DATA		DATETIME	NOT NULL,
	CONSTRAINT	PK_MORTES PRIMARY KEY (ID),
	CONSTRAINT	FK_MORTES_PAIS FOREIGN KEY (ID_PAIS)
	REFERENCES PAIS(ID_Código_ISO2)
);

CREATE TABLE LOG
(
	ID				INT			NOT NULL IDENTITY(1, 1),
	DATA			DATETIME	NOT NULL,
	DESCRICAO		TEXT		NOT NULL,
	CONSTRAINT PK_LOG PRIMARY KEY (ID)
);