-- Panorama diário de quantidade de casos confirmados de COVID-19 dos 10 países do mundo com maiores números.

SELECT TOP 10 PAIS.NOME, SUMARY_PAISES.NEWCONFIRMED
FROM PAIS
INNER JOIN SUMARY_PAISES
ON PAIS.ID = SUMARY_PAISES.ID_PAIS
ORDER BY SUMARY_PAISES.NEWCONFIRMED DESC

-- Panorama diário de quantidade de mortes de COVID-19 dos 10 países do mundo com números.

SELECT TOP 10 PAIS.NOME, SUMARY_PAISES.NEWDEATHS
FROM PAIS
INNER JOIN SUMARY_PAISES
ON PAIS.ID = SUMARY_PAISES.ID_PAIS
ORDER BY SUMARY_PAISES.NEWDEATHS DESC

-- Total de mortes por COVID-19 dos 10 países do mundo com maiores números.

SELECT TOP 10 PAIS.NOME, SUMARY_PAISES.TOTALDEATHS
FROM PAIS
INNER JOIN SUMARY_PAISES
ON PAIS.ID = SUMARY_PAISES.ID_PAIS
ORDER BY SUMARY_PAISES.TOTALDEATHS DESC

-- Total de casos confirmados por COVID-19 dos 10 países do mundo com maiores números.

SELECT TOP 10 PAIS.NOME, SUMARY_PAISES.TOTALCONFIRMED
FROM PAIS
INNER JOIN SUMARY_PAISES
ON PAIS.ID = SUMARY_PAISES.ID_PAIS
ORDER BY SUMARY_PAISES.TOTALCONFIRMED DESC
