/*
    "COUNTRY": "AFGHANISTAN",
    "COUNTRYCODE": "AF",
    "LAT": "33.94",
    "LON": "67.71",
    "CONFIRMED": 0,
    "DEATHS": 0,
    "RECOVERED": 0,
    "ACTIVE": 0,
    "DATE": "2020-01-22T00:00:00Z",
*/
/*
[
    {
        "COUNTRY": "MEXICO",
        "SLUG": "MEXICO",
        "ISO2": "MX"
    },
*/
CREATE TABLE PAIS
(
	ID 				INT				NOT NULL IDENTITY(1, 1),  	--PK
	NOME			VARCHAR(100)     NOT NULL,
	SLUG			VARCHAR(100)     NULL,
	SIGLA           	VARCHAR(2)      NULL,
	CONSTRAINT 		PK_PAIS 	PRIMARY KEY (ID)
);

/*
[{"COUNTRY":"BRAZIL","COUNTRYCODE":"BR",
"PROVINCE":"","CITY":"","CITYCODE":"",
"LAT":"-14.24","LON":"-51.93",
"CASES":0,"STATUS":"CONFIRMED","DATE":"2020-01-22T00:00:00Z"},
*/
CREATE TABLE DADOS_PAISES
(
	ID 				INT				NOT NULL IDENTITY(1, 1),  --PK
	ID_PAIS			INT			NOT NULL,	 	 --FK PAIS
	LAT			DECIMAL			NOT NULL,
	LON			DECIMAL 		NOT NULL,
	CONFIRMED		INT			NULL,
	DEATHS			INT			NULL,
	RECOVERED		INT			NULL,
	ACTIVE			INT			NULL,
	DATE			DATETIME		NOT NULL,
	
	CONSTRAINT 		PK_ID			PRIMARY KEY (ID),
	CONSTRAINT FK_DADOS_PAISES_PAIS 		FOREIGN KEY (ID_PAIS)
		REFERENCES PAIS(ID)
);

CREATE TABLE SUMARY_PAISES
(
	ID 					INT			NOT NULL IDENTITY(1, 1),  --PK
	ID_PAIS				INT			NOT NULL,	 	 --FK PAIS
	NEWCONFIRMED		INT			NULL,
	TOTALCONFIRMED		INT			NULL,
	NEWDEATHS			INT			NULL,
	TOTALDEATHS			INT			NULL,
	NEWRECOVERED		INT		NULL,
	TOTALRECOVERED		INT			NULL,
	DATE			DATETIME		NOT NULL,
	CONSTRAINT 		PK_SUMARY		PRIMARY KEY (ID),
	CONSTRAINT FK_SUMARY_PAIS 		FOREIGN KEY (ID_PAIS)
		REFERENCES PAIS(ID)
);

CREATE TABLE LOG 
(
	ID 				INT				NOT NULL IDENTITY(1, 1), --PK
	DATE		DATETIME	NOT NULL,
	DESCRICAO	TEXT		NOT NULL,
	CONSTRAINT 	PK_LOG		PRIMARY KEY (ID)
);
